// ============================================================================
// REFERENCE RANGES DOCUMENTATION
// Source: Dynacare Labs (Ontario, Canada) - Adult Male Reference Ranges
// ============================================================================
export const REFERENCE_RANGES = {
  // COMPLETE BLOOD COUNT (CBC)
  hemoglobin: {
    name: 'Hemoglobin',
    min: 129,
    max: 165,
    unit: 'g/L',
    category: 'cbc',
    description: 'Oxygen-carrying protein in red blood cells',
    clinicalNotes:
      'Low values may indicate anemia; high values may indicate dehydration or polycythemia',
    optimalRange: { min: 140, max: 160 },
  },
  hematocrit: {
    name: 'Hematocrit',
    min: 0.39,
    max: 0.49,
    unit: 'L/L',
    category: 'cbc',
    description: 'Percentage of blood volume occupied by red blood cells',
    clinicalNotes: 'Reflects hydration status and red blood cell mass',
    optimalRange: { min: 0.42, max: 0.47 },
  },
  rbc_count: {
    name: 'RBC Count',
    min: 4.2,
    max: 5.8,
    unit: 'x10¹²/L',
    category: 'cbc',
    description: 'Number of red blood cells per liter of blood',
    clinicalNotes: 'Measures oxygen-carrying capacity of blood',
    optimalRange: { min: 4.5, max: 5.5 },
  },
  mcv: {
    name: 'MCV (Mean Cell Volume)',
    min: 80,
    max: 98,
    unit: 'fL',
    category: 'cbc',
    description: 'Average size of red blood cells',
    clinicalNotes:
      'Helps classify type of anemia - low MCV suggests iron deficiency, high MCV suggests B12/folate deficiency',
    optimalRange: { min: 85, max: 95 },
  },
  mch: {
    name: 'MCH (Mean Cell Hemoglobin)',
    min: 24,
    max: 33,
    unit: 'pg',
    category: 'cbc',
    description: 'Average amount of hemoglobin per red blood cell',
    clinicalNotes: 'Correlates with MCV in classifying anemias',
    optimalRange: { min: 27, max: 31 },
  },
  mchc: {
    name: 'MCHC',
    min: 313,
    max: 344,
    unit: 'g/L',
    category: 'cbc',
    description: 'Average concentration of hemoglobin in red blood cells',
    clinicalNotes: 'Low values suggest hypochromic anemia',
    optimalRange: { min: 320, max: 340 },
  },
  rbc_distribution_width: {
    name: 'RBC Distribution Width',
    min: 12.5,
    max: 17.3,
    unit: '%',
    category: 'cbc',
    description: 'Variation in red blood cell size',
    clinicalNotes: 'Elevated in mixed anemias and some chronic conditions',
    optimalRange: { min: 12.5, max: 14.5 },
  },
  wbc_count: {
    name: 'WBC Count',
    min: 3.2,
    max: 9.4,
    unit: 'x10⁹/L',
    category: 'cbc',
    description: 'Total white blood cell count',
    clinicalNotes:
      'Elevated in infection/inflammation; low in immunodeficiency or bone marrow issues',
    optimalRange: { min: 4.0, max: 8.0 },
  },
  platelet_count: {
    name: 'Platelet Count',
    min: 155,
    max: 372,
    unit: 'x10⁹/L',
    category: 'cbc',
    description: 'Blood clotting cells',
    clinicalNotes: 'Low increases bleeding risk; high may increase clotting risk',
    optimalRange: { min: 180, max: 320 },
  },
  mpv: {
    name: 'Mean Platelet Volume',
    min: 4.0,
    max: 14.0,
    unit: 'fL',
    category: 'cbc',
    description: 'Average size of platelets',
    clinicalNotes: 'Larger platelets are younger and more active',
    optimalRange: { min: 7.0, max: 11.0 },
  },

  // WBC DIFFERENTIAL
  neutrophils: {
    name: 'Neutrophils',
    min: 1.4,
    max: 6.3,
    unit: 'x10⁹/L',
    category: 'wbc',
    description: 'First-line defense against bacterial infections',
    clinicalNotes: 'Elevated in bacterial infection; low increases infection risk',
    optimalRange: { min: 2.0, max: 5.0 },
  },
  lymphocytes: {
    name: 'Lymphocytes',
    min: 1.0,
    max: 2.9,
    unit: 'x10⁹/L',
    category: 'wbc',
    description: 'Immune cells for viral infections and long-term immunity',
    clinicalNotes:
      'Low counts (lymphopenia) may indicate viral infection, stress, or immune disorders',
    optimalRange: { min: 1.2, max: 2.5 },
  },
  monocytes: {
    name: 'Monocytes',
    min: 0.2,
    max: 0.8,
    unit: 'x10⁹/L',
    category: 'wbc',
    description: 'Immune cells that become macrophages in tissues',
    clinicalNotes: 'Elevated in chronic infections and inflammatory conditions',
    optimalRange: { min: 0.3, max: 0.7 },
  },
  eosinophils: {
    name: 'Eosinophils',
    min: 0.0,
    max: 0.5,
    unit: 'x10⁹/L',
    category: 'wbc',
    description: 'Involved in allergic reactions and parasitic infections',
    clinicalNotes: 'Elevated in allergies, asthma, and parasitic infections',
    optimalRange: { min: 0.0, max: 0.3 },
  },
  basophils: {
    name: 'Basophils',
    min: 0.0,
    max: 0.09,
    unit: 'x10⁹/L',
    category: 'wbc',
    description: 'Involved in allergic and inflammatory responses',
    clinicalNotes: 'Rarely clinically significant unless markedly elevated',
    optimalRange: { min: 0.0, max: 0.05 },
  },

  // METABOLIC PANEL
  glucose_fasting: {
    name: 'Fasting Glucose',
    min: 3.6,
    max: 6.0,
    unit: 'mmol/L',
    category: 'metabolic',
    description: 'Blood sugar level after fasting',
    clinicalNotes: '6.1-6.9 indicates prediabetes; ≥7.0 indicates diabetes',
    optimalRange: { min: 4.0, max: 5.5 },
  },
  creatinine: {
    name: 'Creatinine',
    min: 60,
    max: 110,
    unit: 'µmol/L',
    category: 'metabolic',
    description: 'Waste product from muscle metabolism, filtered by kidneys',
    clinicalNotes: 'Elevated levels may indicate reduced kidney function; affected by muscle mass',
    optimalRange: { min: 70, max: 100 },
  },
  egfr: {
    name: 'eGFR',
    min: 60,
    max: null,
    unit: 'mL/min/1.73m²',
    category: 'metabolic',
    description: 'Estimated glomerular filtration rate - kidney function measure',
    clinicalNotes: '>90 is normal; 60-89 mildly reduced; <60 indicates chronic kidney disease',
    optimalRange: { min: 90, max: 120 },
  },
  uric_acid: {
    name: 'Uric Acid',
    min: 220,
    max: 512,
    unit: 'µmol/L',
    category: 'metabolic',
    description: 'Waste product from purine metabolism',
    clinicalNotes:
      'Elevated levels increase risk of gout and kidney stones; associated with cardiovascular risk',
    optimalRange: { min: 250, max: 420 },
  },
  sodium: {
    name: 'Sodium',
    min: 136,
    max: 146,
    unit: 'mmol/L',
    category: 'metabolic',
    description: 'Electrolyte important for fluid balance and nerve function',
    clinicalNotes:
      'Abnormal levels affect fluid balance, blood pressure, and neurological function',
    optimalRange: { min: 138, max: 144 },
  },
  bilirubin_total: {
    name: 'Total Bilirubin',
    min: null,
    max: 23,
    unit: 'µmol/L',
    category: 'liver',
    description: 'Breakdown product of red blood cells processed by liver',
    clinicalNotes: 'Elevated in liver disease, bile duct obstruction, or hemolysis',
    optimalRange: { min: 5, max: 17 },
  },

  // LIPID PANEL
  cholesterol_total: {
    name: 'Total Cholesterol',
    min: null,
    max: 5.2,
    unit: 'mmol/L',
    category: 'lipid',
    description: 'Total cholesterol in blood',
    clinicalNotes: 'Should be interpreted with HDL, LDL, and triglycerides for cardiovascular risk',
    optimalRange: { min: 3.5, max: 4.5 },
  },
  triglycerides: {
    name: 'Triglycerides',
    min: null,
    max: 1.7,
    unit: 'mmol/L',
    category: 'lipid',
    description: 'Fat molecules in blood',
    clinicalNotes:
      'Elevated by diet, alcohol, obesity, and diabetes; increases cardiovascular risk',
    optimalRange: { min: 0.5, max: 1.2 },
  },
  hdl: {
    name: 'HDL Cholesterol',
    min: 1.0,
    max: null,
    unit: 'mmol/L',
    category: 'lipid',
    description: "'Good' cholesterol - removes cholesterol from arteries",
    clinicalNotes: 'Higher is better; <1.0 indicates increased cardiovascular risk',
    optimalRange: { min: 1.2, max: 2.0 },
  },
  ldl: {
    name: 'LDL Cholesterol',
    min: null,
    max: 3.5,
    unit: 'mmol/L',
    category: 'lipid',
    description: "'Bad' cholesterol - deposits in artery walls",
    clinicalNotes: 'Lower is better; target depends on cardiovascular risk factors',
    optimalRange: { min: 1.5, max: 2.5 },
  },
  non_hdl: {
    name: 'Non-HDL Cholesterol',
    min: null,
    max: 4.2,
    unit: 'mmol/L',
    category: 'lipid',
    description: 'Total cholesterol minus HDL - all atherogenic cholesterol',
    clinicalNotes: 'Better predictor of cardiovascular risk than LDL alone',
    optimalRange: { min: 2.0, max: 3.5 },
  },

  // LIVER FUNCTION
  alt: {
    name: 'ALT (Alanine Aminotransferase)',
    min: null,
    max: 46,
    unit: 'U/L',
    category: 'liver',
    description: 'Liver enzyme released when liver cells are damaged',
    clinicalNotes: 'Elevated in liver disease, fatty liver, medications, and muscle injury',
    optimalRange: { min: 10, max: 30 },
  },
  alp: {
    name: 'ALP (Alkaline Phosphatase)',
    min: 40,
    max: 129,
    unit: 'U/L',
    category: 'liver',
    description: 'Enzyme found in liver, bone, and other tissues',
    clinicalNotes: 'Elevated in bile duct obstruction, bone disorders, and liver disease',
    optimalRange: { min: 50, max: 100 },
  },

  // THYROID
  tsh: {
    name: 'TSH (Thyroid Stimulating Hormone)',
    min: 0.35,
    max: 5.0,
    unit: 'mIU/L',
    category: 'thyroid',
    description: 'Pituitary hormone that regulates thyroid function',
    clinicalNotes: 'High TSH suggests hypothyroidism; low TSH suggests hyperthyroidism',
    optimalRange: { min: 1.0, max: 3.0 },
  },

  // INFLAMMATORY MARKERS
  rheumatoid_factor: {
    name: 'Rheumatoid Factor',
    min: null,
    max: 14,
    unit: 'IU/mL',
    category: 'inflammatory',
    description: 'Autoantibody associated with rheumatoid arthritis',
    clinicalNotes: 'Can be elevated in other autoimmune conditions and chronic infections',
    optimalRange: { min: 0, max: 10 },
  },
  sedimentation_rate: {
    name: 'ESR (Sedimentation Rate)',
    min: 0,
    max: 15,
    unit: 'mm/hr',
    category: 'inflammatory',
    description: 'Non-specific marker of inflammation',
    clinicalNotes: 'Elevated in infection, autoimmune disease, and malignancy; increases with age',
    optimalRange: { min: 0, max: 10 },
  },

  // URINALYSIS
  specific_gravity: {
    name: 'Specific Gravity (Urine)',
    min: 1.005,
    max: 1.03,
    unit: '',
    category: 'urine',
    description: 'Concentration of urine',
    clinicalNotes: 'Low suggests overhydration or kidney issues; high suggests dehydration',
    optimalRange: { min: 1.01, max: 1.025 },
  },
  ph_urine: {
    name: 'pH (Urine)',
    min: 5.0,
    max: 8.0,
    unit: '',
    category: 'urine',
    description: 'Acidity/alkalinity of urine',
    clinicalNotes: 'Affected by diet, medications, and metabolic conditions',
    optimalRange: { min: 5.5, max: 7.0 },
  },
  urobilinogen: {
    name: 'Urobilinogen',
    min: 3.2,
    max: 16,
    unit: 'µmol/L',
    category: 'urine',
    description: 'Bilirubin breakdown product in urine',
    clinicalNotes: 'Elevated in hemolysis and liver disease',
    optimalRange: { min: 3.2, max: 10 },
  },
};

// Helper to get display label
export const getMetricLabel = (key) => REFERENCE_RANGES[key]?.name || key;
